"""
This file is auto-generated by Chargebee.
For more information on how to make changes to this file, please see the README.
Reach out to dx@chargebee.com for any questions.
Copyright 2026 Chargebee Inc.
"""

from __future__ import annotations

from typing import Any, Mapping, Protocol, runtime_checkable

from chargebee.api_error import APIError

from .types import (
    CHARGEBEE_SDK_NAME,
    BuildRequestTelemetryContextInput,
    RequestTelemetryContext,
    RequestTelemetryError,
    RequestTelemetryResult,
    TELEMETRY_SPAN_NAME_PREFIX,
    TelemetryAttributeKeys,
)


@runtime_checkable
class TelemetryAdapter(Protocol):
    """
    Optional telemetry adapter for observability integrations (e.g. OpenTelemetry).

    When not configured, the SDK skips all telemetry work — zero overhead. The SDK
    stores the adapter by reference and never clones or deep-copies it.

    Implementations may inject W3C trace context headers (traceparent, tracestate)
    into request_headers during on_request_start.
    """

    def on_request_start(
        self,
        context: RequestTelemetryContext,
        request_headers: dict[str, str],
    ) -> Any:
        """Called once per SDK API call before the request is sent (including retries)."""

    def on_request_end(self, handle: Any, result: RequestTelemetryResult) -> None:
        """Called once per SDK API call after the final response or terminal failure."""


class NoOpTelemetryAdapter:
    def on_request_start(
        self,
        context: RequestTelemetryContext,
        request_headers: dict[str, str],
    ) -> None:
        return None

    def on_request_end(self, handle: Any, result: RequestTelemetryResult) -> None:
        return None


NO_OP_TELEMETRY_ADAPTER = NoOpTelemetryAdapter()


def build_span_name(resource: str, operation: str) -> str:
    return f"{TELEMETRY_SPAN_NAME_PREFIX}.{resource}.{operation}"


def resolve_chargebee_api_version(api_path: str) -> str:
    return "v1" if api_path == "/api/v1" else "v2"


def build_request_start_span_attributes(
    input: BuildRequestTelemetryContextInput,
) -> dict[str, str]:
    return {
        TelemetryAttributeKeys.URL_FULL: input.http_url,
        TelemetryAttributeKeys.HTTP_REQUEST_METHOD: input.http_method,
        TelemetryAttributeKeys.SERVER_ADDRESS: input.server_address,
        TelemetryAttributeKeys.CHARGEBEE_SITE: input.chargebee_site,
        TelemetryAttributeKeys.CHARGEBEE_API_VERSION: input.chargebee_api_version,
        TelemetryAttributeKeys.CHARGEBEE_RESOURCE: input.resource,
        TelemetryAttributeKeys.CHARGEBEE_OPERATION: input.operation,
        TelemetryAttributeKeys.CHARGEBEE_SDK_NAME: CHARGEBEE_SDK_NAME,
        TelemetryAttributeKeys.CHARGEBEE_SDK_VERSION: input.sdk_version,
    }


def build_request_end_span_attributes(
    http_status_code: int,
    error: RequestTelemetryError | None,
) -> dict[str, str | int]:
    attributes: dict[str, str | int] = {
        TelemetryAttributeKeys.HTTP_RESPONSE_STATUS_CODE: http_status_code,
    }

    if error is not None:
        attributes[TelemetryAttributeKeys.ERROR_TYPE] = str(http_status_code)
        if error.chargebee_error_code is not None:
            attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_CODE] = (
                error.chargebee_error_code
            )
        if error.chargebee_api_error_type is not None:
            attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_TYPE] = (
                error.chargebee_api_error_type
            )
        if error.chargebee_error_param is not None:
            attributes[TelemetryAttributeKeys.CHARGEBEE_ERROR_PARAM] = (
                error.chargebee_error_param
            )

    return attributes


def build_request_telemetry_context(
    input: BuildRequestTelemetryContextInput,
) -> RequestTelemetryContext:
    return RequestTelemetryContext(
        span_name=build_span_name(input.resource, input.operation),
        resource=input.resource,
        operation=input.operation,
        http_method=input.http_method,
        http_url=input.http_url,
        server_address=input.server_address,
        chargebee_site=input.chargebee_site,
        chargebee_api_version=input.chargebee_api_version,  # type: ignore[arg-type]
        sdk_name=CHARGEBEE_SDK_NAME,
        sdk_version=input.sdk_version,
        start_attributes=build_request_start_span_attributes(input),
    )


def build_request_telemetry_result(
    http_status_code: int,
    duration_ms: int,
    error: RequestTelemetryError | None,
) -> RequestTelemetryResult:
    return RequestTelemetryResult(
        http_status_code=http_status_code,
        duration_ms=duration_ms,
        error=error,
        end_attributes=build_request_end_span_attributes(http_status_code, error),
    )


def extract_request_telemetry_error(err: BaseException | None) -> RequestTelemetryError | None:
    if err is None:
        return None

    message = str(err) if str(err) else "Chargebee API request failed"

    if isinstance(err, APIError):
        return RequestTelemetryError(
            message=message,
            chargebee_error_code=err.api_error_code,
            chargebee_api_error_type=err.type,
            chargebee_error_param=err.param,
        )

    return RequestTelemetryError(message=message)


def extract_http_status_code(err: BaseException | None) -> int | None:
    if isinstance(err, APIError):
        return err.http_status_code
    return None
