"""
This file is auto-generated by Chargebee.
For more information on how to make changes to this file, please see the README.
Reach out to dx@chargebee.com for any questions.
Copyright 2026 Chargebee Inc.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Mapping, Union

CHARGEBEE_SDK_NAME = "chargebee-python"
TELEMETRY_SPAN_NAME_PREFIX = "chargebee"


class TelemetryAttributeKeys:
    """Span attribute keys shared across Chargebee SDKs."""

    HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX = "http.request.header."
    CHARGEBEE_TELEMETRY_HEADER_PREFIX = "chargebee-"
    CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX = "chargebee-request-origin-"

    URL_FULL = "url.full"
    HTTP_REQUEST_METHOD = "http.request.method"
    HTTP_RESPONSE_STATUS_CODE = "http.response.status_code"
    SERVER_ADDRESS = "server.address"
    ERROR_TYPE = "error.type"
    CHARGEBEE_SITE = "chargebee.site"
    CHARGEBEE_API_VERSION = "chargebee.api_version"
    CHARGEBEE_RESOURCE = "chargebee.resource"
    CHARGEBEE_OPERATION = "chargebee.operation"
    CHARGEBEE_SDK_NAME = "chargebee.sdk.name"
    CHARGEBEE_SDK_VERSION = "chargebee.sdk.version"
    CHARGEBEE_ERROR_CODE = "chargebee.error.code"
    CHARGEBEE_ERROR_TYPE = "chargebee.error.type"
    CHARGEBEE_ERROR_PARAM = "chargebee.error.param"


@dataclass(frozen=True)
class RequestTelemetryError:
    message: str
    chargebee_error_code: str | None = None
    chargebee_api_error_type: str | None = None
    chargebee_error_param: str | None = None


@dataclass(frozen=True)
class RequestTelemetryContext:
    span_name: str
    resource: str
    operation: str
    http_method: str
    http_url: str
    server_address: str
    chargebee_site: str
    chargebee_api_version: Literal["v1", "v2"]
    sdk_name: str
    sdk_version: str
    start_attributes: Mapping[str, str]


@dataclass(frozen=True)
class RequestTelemetryResult:
    http_status_code: int
    duration_ms: int
    error: RequestTelemetryError | None
    end_attributes: Mapping[str, Union[str, int]]


@dataclass(frozen=True)
class BuildRequestTelemetryContextInput:
    resource: str
    operation: str
    http_method: str
    http_url: str
    server_address: str
    chargebee_site: str
    chargebee_api_version: Literal["v1", "v2"]
    sdk_version: str
    request_headers: Mapping[str, str] | None = None
